version: 0.0
os: linux
files:
  - source: ./target/webserver-0.0.1-SNAPSHOT.jar/webserver-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/javaapp
  - source: ./cloudwatch-config.json
    destination: /opt
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
  - location: ./codedeploy/afterinstall.sh
    timeout: 180
    runas: root
  ApplicationStart:
  - location: ./codedeploy/applicationstart.sh
    timeout: 180
    runas: root
  BeforeInstall:
  - location: ./codedeploy/beforeinstall.sh
    timeout: 180
    runas: root