name: Java CI

on: 
  push:
  pull_request:

jobs:
  build:
    name: java compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.322+6'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package spring-boot:repackage -DskipTests
      - name: publish jar
        uses: actions/upload-artifact@v2-preview
        with:
          name: "webserver-0.0.1-SNAPSHOT.jar"
          path: target/*.jar
      # - name: fetch artifact
      #   uses: actions/download-artifact@master
      #   with:
      #     name: "webserver-0.0.1-SNAPSHOT.jar"
      #     path: target/webserver-0.0.1-SNAPSHOT.jar
      - name: ami packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-var-file=packer/vars.json packer/ami.json"
        env: 
          PACKER_LOG: 1