name: Java CI

on: [push | pull_request] 

jobs:
  build:
    name: java compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.322+6'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn compile
